### ISSUE TITLE
Minimize Dependencies (i.e. disable default features or remove dependencies if possible)

### ISSUE THREAD

**Issue by AS1100K** [AS1100K/bevy-discord#12]
Currently `Cargo.toml` is pretty good, it has few dependencies, but try to minimize them further

<details>
<summary>Old <code>Cargo.toml</code></summary>

```toml
[dependencies]
bevy_app = "0.15"
bevy_ecs = "0.15"
flume = "0.11"
serenity = { version = "0.12", features = [
    "gateway",
    "framework",
    "model",
], optional = true }
paste = "1"
tracing = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "rt"] }
discord-sdk = { version = "0.4", optional = true }
async-trait = { version = "0.1", optional = true }
```

</details>

<details open>
<summary><i><b>EDIT:</b> Current <code>Cargo.toml</code></i></summary>

```toml
[dependencies]
bevy_app = { version = "0.15", default-features = false }
bevy_ecs = { version = "0.15", default-features = false }
flume = "0.11"
serenity = { version = "0.12", features = [
    "gateway",
    "framework",
    "model",
], optional = true }
paste = "1"
tracing = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "rt"] }
discord-sdk = { version = "0.4", optional = true }
async-trait = { version = "0.1", optional = true }

[dev-dependencies]
bevy = "0.15"
serde_json = "1"
```
</details>

Also, `paste` is unmaintained, [issue #2215 on advisory-db](https://github.com/rustsec/advisory-db/pull/2215)
